# Exercício:

## 01 – Dados as operações abaixo, qual o resultado da operação lógica: 
p and q and r and s and t?
<br>
<br>Como os operadores lógicos podem ser usados para inverter o resultado?

<br>p = 2.0 + 3.0 / 5.0 == 10
<br>q = (p + 10.2) - 5.0 * 2.0 <= 2.9
<br>r = 10 <= p / q + 33.8 < 100
<br>s = 5 != p / (q + r)
<br>t = 33 == s * 2

In [14]:
p = 2.0 + 3.0 / 5.0 == 10
q = (p + 10.2) - 5.0 * 2.0 <= 2.9
r = 10 <= p / q + 33.8 < 100
s = 5 != p / (q + r)
t = 33 == s * 2

resultado = (p and q and r and s and t)
inverter = (p or q or r or s or t)
print (f"(p and q and r and s and t) -> {resultado}")

print (f"Para inverter o resultado pode-se usar o operador lógico 'or': ")
print (f"(p or q or r or s or t) -> {inverter}")

(p and q and r and s and t) -> False
Para inverter o resultado pode-se usar o operador lógico 'or':
(p or q or r or s or t) -> True

## 02 – Usando apenas o operador or, qual seria o resultado final das operações abaixo? Como deve ser usado o not para inverter o resultado?

<br>p = ('a',1,True,'b',0,False) != ('a',True,1,'b',False,0)
<br>q = ['a',1,True,'b',0,False] != ('a',True,1,'b',False,0)
<br>r = ['a',1,True,'b',0,False] != ['a',True,1,'b',False,0]
<br>s = ['a',1,True,'b',0,False] > ['a',True,1]
<br>t = ['a',1,True,'b',0,False] == 1
<br>u = ['a',True,1] <= ['a',True,1] < ['a',1,True,'b',0,False]

In [20]:
p_dois = ('a',1,True,'b',0,False) != ('a',True,1,'b',False,0)
q_dois = ['a',1,True,'b',0,False] != ('a',True,1,'b',False,0)
r_dois = ['a',1,True,'b',0,False] != ['a',True,1,'b',False,0]
s_dois = ['a',1,True,'b',0,False] > ['a',True,1]
t_dois = ['a',1,True,'b',0,False] == 1
u_dois = ['a',True,1] <= ['a',True,1] < ['a',1,True,'b',0,False]

resultado_2 = (p_dois or q_dois or r_dois or s_dois or t_dois or u_dois)
resultado_3 = not (p_dois or q_dois or r_dois or s_dois or t_dois or u_dois)
print (f"Utilizando apenas o operador 'or' o resultado das operações abaixo é: {resultado_2}")
print (f"O 'not' deve ser usado dessa forma para inverter o resultado: 'not (p_dois or q_dois or r_dois or s_dois or t_dois or u_dois)' -> {resultado_3}")

Utilizando apenas o operador 'or' o resultado das operações abaixo é: True
O 'not' deve ser usado dessa forma para inverter o resultado: 'not (p_dois or q_dois or r_dois or s_dois or t_dois or u_dois)' -> False

## 03 – No exercício 3 da aula 8 foi importado um arquivo .csv para um objeto da classe DataFrame pandas. Importe aqui o mesmo objeto e arredonde e edite o index como realizado no exercício 3 da aula 8. Usando operadores responda, a segunda linha é igual a terceira ou a terceira linha é igual a quarta?

In [31]:
import pandas as pd

df_atv7 = pd.read_csv("./df_atv7.csv", index_col= "Unnamed: 0").round(3)

comparacao = (
    (df_atv7.iloc[1, :] == df_atv7.iloc[2, :]).all() or
    (df_atv7.iloc[2, :] == df_atv7.iloc[3, :]).all()
)

print(comparacao)

False

## 04 – Usando operadores verifique se todos os valores contidos na primeira linha são maiores ou iguais a 10.

In [34]:
print ((df_atv7.iloc[0, :] >= 10).all())

False

## 05 – Usando operadores verifique se todos os valores contidos na terceira coluna estão entre 0 inclusive e 40.

In [37]:
print ((df_atv7.iloc[:, 2] >= 0).all() and (df_atv7.iloc[:, 2] < 40).all())

True

## 06 – Usando operadores verifique se algum dos valores contidos na última linha está acima de 10.

In [40]:
print ((df_atv7.iloc[-1, :] > 10).any())

False

## 07 – Recupere a DataFrame contendo apenas valores que estejam acima de 5 e abaixo de 7.

In [43]:
df_atv7[(df_atv7 > 5) & (df_atv7 < 7)]

         1      2   3      4  Médias
0      NaN    NaN NaN    NaN     NaN
1      NaN    NaN NaN  5.893     NaN
2      NaN    NaN NaN    NaN     NaN
3      NaN    NaN NaN    NaN     NaN
4      NaN  5.893 NaN    NaN     NaN
Médias NaN    NaN NaN    NaN   5.015

## 08 – Recupere a DataFrame contendo apenas valores que estejam abaixo de 5 inclusive ou acima de 7.

In [45]:
df_atv7[(df_atv7 >= 5) | (df_atv7 < 7)]

             1      2       3      4  Médias
0        2.600  2.800  34.729  0.069  10.050
1        0.139  1.612   1.673  5.893   2.329
2        0.263  0.372   2.600  2.800   1.509
3       34.729  0.069   0.139  1.612   9.137
4        1.673  5.893   0.263  0.372   2.050
Médias   7.881  2.149   7.881  2.149   5.015

## 09 – Converta as duas últimas colunas do objeto DataFrame para dois objetos da classe numpy array. Algum dos valores contidos no primeiro array estão entre 2 inclusive e 5 inclusive?

In [49]:
import numpy as np 

array1 = np.array(df_atv7.iloc[:, -2])
array2 = np.array(df_atv7.iloc[:, -1])
print(np.any((array1 >= 2) & (array1 <= 5)))

True

## 10 – Os valores contidos nos dois arrays são superiores à -1 e inferiores à 12?

In [54]:
print((np.all((array1 > -1) & (array1 < 12))) & (np.all((array2 > -1) & (array2 < 12))) )

True